name: Deploy to Server

on:
  push:
    branches:
      - master # Deploy on branches
      - feature/localisation
      - feature/reservation
      - feature/user

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/nfs/micro-service/quick-serve/reservation_api

            echo "Pulling latest code..."
            git pull

            echo "Stoppin  g existing Docker container..."
            docker stop reservation_api_container || true
            docker rm reservation_api_container || true

            echo "Building Docker image..."
            docker build -t reservation_api_image .

            echo "Running Docker container..."
            docker run -d --name reservation_api_container -p 8082:8080 reservation_api_image
