name: Deploy to Server

on:
  push:
    branches:
      - feature/payment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/nfs/micro-service/quick-serve/evaluation_api

            echo "Pulling latest code..."
            git pull

            echo "Stoppin  g existing Docker container..."
            docker stop evaluation_api_container || true
            docker rm evaluation_api_container || true

            echo "Building Docker image..."
            docker build -t evaluation_api_image .

            echo "Running Docker container..."
            docker run -d --name evaluation_api_container -p 8083:8080 evaluation_api_image
